package command;

public enum CommandType {
    SIGNIN, SIGNUP, SAVE,
    BUY, SELL, SEARCH, SHOWALL,
    REQUEST_GAME, CREATE_GAME, MOVE, ENDTURN, ATTACK, INSERT,SELECT, EXIT_GAME,
    CREATE_CUSTOM
    ;
}
