package command;

public enum CommandType {
    SIGNIN, SIGNUP, SAVE, SCORE_BOARD, LOGOUT,
    BUY, SELL, SEARCH, SHOWALL,
    REQUEST_GAME, CREATE_GAME, MOVE, ENDTURN, ATTACK, INSERT,SELECT, EXIT_GAME,
    CREATE_CUSTOM, CHAT, END_GAME, GET_LAST_GAME
    ;
}
