package Model;

public enum BuffType {
    HOLY,
    ATTACK_POWER, HEALTH_POWER,
    POSION,
    ATTACK_WEAKNESS, HEALTH_WEAKNESS,
    STUN,
    DISARM,
    ATTACK_TO_ENEMY,
    CELL_EFFECT_HOLY,
    CELL_EFFECT_POSION,
    CELL_EFFECT_FIERY,;
}
