package Model;

public enum BuffType {
    HOLY,
    ATTACK_POWER, HEALTH_POWER,
    POISON,
    ATTACK_WEAKNESS, HEALTH_WEAKNESS,
    STUN,
    DISARM,
    DISPEL,
    ATTACK_TO_ENEMY,
    CELL_EFFECT_HOLY,
    CELL_EFFECT_POISON,
    CELL_EFFECT_FIERY,
    REMOVE_ENEMIES_BUFFS,
    REMOVE_INSIDERS_BUFFS,
    KILL,
    INCREASE_MANA,
    ATTACK_INSERT,
    NONE,

}
