package Model;

public enum RequestType {
    EXIT, INVALID_COMMAND, HELP,
    ACCOUNT_CREATE_ACCOUNT, ACCOUNT_LOGIN, ACCOUNT_SHOWlEADERBOARD, ACCOUNT_SAVE, ACCOUNT_LOGOUT,
    MAIN_COLLECTION, MAIN_SHOP, MAIN_BATTLE,
    COLLECTION_SHOW_DECK, COLLECTION_SHOW_ALL_DECKS, COLLECTION_SELECT_DECK, COLLECTION_VALIDATE_DECK,
    COLLECTION_REMOVE, COLLECTION_ADD, COLLECTION_DELETE_DECK, COLLECTION_CREATE_DECK, COLLECTION_SAVE,
    COLLECTION_SEARCH, COLLECTION_SHOW

}
