package Model;

public enum RequestType {
    EXIT, INVALID_COMMAND, HELP,
    ACCOUNT_CREATE_ACCOUNT, ACCOUNT_LOGIN, ACCOUNT_SHOWlEADERBOARD, ACCOUNT_SAVE, ACCOUNT_LOGOUT,
    MAIN_COLLECTION, MAIN_SHOP, MAIN_BATTLE;
}
