package Model.enums;

public enum TargetCommunity {
    ONE_ENEMY_FORCE,
    ALL_ENEMY_FORCES,
    ALL_ENEMY_FORCES_IN_COLUMN,
    ONE_ENEMY_FORCE_RANDOM,
    ONE_INSIDER_FORCE_RANDOM,
    ONE_INSIDER_FORCE,
    ALL_INSIDER_FORCES,
    ENEMY_OR_INSIDER_FORCE,
    ENEMY_HERO,
    INSIDER_HERO,
    TWO_IN_TWO,
    ONE_CELL,
    THREE_IN_THREE,
    OWN,
    ALL_ENEMY_FORCES_IN_ROW,
    ALL_ENEMY_FORCES_CLOSE,
    RANGED_HYBRID,
    JUST_MELEE,
    OWN_AND_INSIDER_FORCES_CLOSE,
    NONE,
}
